name: "CI: dotnet-service"

on:
  push:
    branches: [main]
    paths:
      - "services/dotnet-service/**"
      - ".github/workflows/ci-dotnet.yml"
  pull_request:
    paths:
      - "services/dotnet-service/**"
      - ".github/workflows/ci-dotnet.yml"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.run_id || 'main' }}
  cancel-in-progress: false

jobs:
  ci:
    uses: mmastersvz/central-ci/.github/workflows/lib-ci-dotnet.yml@main
    with:
      app-name:     dotnet-service
      app-dir:      services/dotnet-service
      project-path: src/DotnetService
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
