name: "CI: go-service"

on:
  push:
    branches: [main]
    paths:
      - "services/go-service/**"
      - ".github/workflows/ci-go.yml"
  pull_request:
    paths:
      - "services/go-service/**"
      - ".github/workflows/ci-go.yml"

  workflow_dispatch:

concurrency:
  group: ${{ github.event_name == 'pull_request' && github.run_id || 'release-main' }}
  cancel-in-progress: false

jobs:
  ci:
    uses: mmastersvz/central-ci/.github/workflows/lib-ci-go.yml@main
    with:
      app-name: "go-service"
      app-dir: "services/go-service"
      # tool-versions-path: ./.tool-versions
    secrets: inherit
